import { roboto } from "@/lib/fonts";
import "./globals.css";

export const metadata = {
  title: "TosChat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} text-white bg-gray-900 min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
